apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3111
  selector:
    app: techtrends